### ISSUE TITLE
Transfer to Organization

### ISSUE THREAD

**Issue by schnittstabil** [middlewares/awesome-psr15-middlewares#1]
@oscarotero I don't know if you know [what an awesome list is](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

However, I think it would be even more awesome, if we could transfer it to the [Middlewares Organization](https://github.com/middlewares).
Of course, I don't want to stop maintaining this list, but I think your awesome PSR-15 Middlewares and this list may get even more attention under the organization.

Are you interested?

**Comment by oscarotero** [comment]
Sure!
This can be a good resource for people getting started in psr-15, not only because the package links but also the articles.
I'll add you as a member of the organization.
Thanks.

**Comment by schnittstabil** [comment]
@oscarotero Many thanks.

@eusonlito, @mindplay-dk, @oscarotero, @sbol-coolblue: Hello, everybody. PRs and suggestions are always welcome :beers:
